; Note: this text file contains Unicode character encoded in UTF8.

[global]
basedir = d:/testdir

[section1]
key1 = 11
key2 = 12
keym = val first line
	val second line

greet words = Hello, my friend!

[section2]
; space-chars around '=' is optional
key1=21
key2  =  22
keym = 
	val line one
;	1st embedded comment line in key's value
	val line two
;	2nd embedded comment line in key's value
	val line three
; Below is a key with empty value.
emptykey =  
endkey =    endval
; End of section 2

[unicodes]
key1 = ABC电

!A deliberate invalid line.
