#ifndef __tCB_GETCURSEL_iversion_h_
#define __tCB_GETCURSEL_iversion_h_

#define tCB_GETCURSEL_VMAJOR 1
#define tCB_GETCURSEL_VMINOR 0
#define tCB_GETCURSEL_VPATCH 0
#define tCB_GETCURSEL_VTAIL  1

#define tCB_GETCURSELstr__(n) #n
#define tCB_GETCURSELstr(n) tCB_GETCURSELstr__(n)

// The following 4 are used in .rc
#define tCB_GETCURSEL_VMAJORs tCB_GETCURSELstr(tCB_GETCURSEL_VMAJOR)
#define tCB_GETCURSEL_VMINORs tCB_GETCURSELstr(tCB_GETCURSEL_VMINOR)
#define tCB_GETCURSEL_VPATCHs tCB_GETCURSELstr(tCB_GETCURSEL_VPATCH)
#define tCB_GETCURSEL_VTAILs  tCB_GETCURSELstr(tCB_GETCURSEL_VTAIL)

#define tCB_GETCURSEL_NAME "tCB_GETCURSEL"

enum {
	tCB_GETCURSEL_vmajor = tCB_GETCURSEL_VMAJOR,
	tCB_GETCURSEL_vminor = tCB_GETCURSEL_VMINOR,
	tCB_GETCURSEL_vpatch = tCB_GETCURSEL_VPATCH,
	tCB_GETCURSEL_vtail = tCB_GETCURSEL_VTAIL,
};


#endif
