#ifndef __testTTM_WINDOWFROMPOINT_iversion_h_
#define __testTTM_WINDOWFROMPOINT_iversion_h_

#define testTTM_WINDOWFROMPOINT_VMAJOR 1
#define testTTM_WINDOWFROMPOINT_VMINOR 0
#define testTTM_WINDOWFROMPOINT_VPATCH 0
#define testTTM_WINDOWFROMPOINT_VTAIL  1

#define testTTM_WINDOWFROMPOINTstr__(n) #n
#define testTTM_WINDOWFROMPOINTstr(n) testTTM_WINDOWFROMPOINTstr__(n)

// The following 4 are used in .rc
#define testTTM_WINDOWFROMPOINT_VMAJORs testTTM_WINDOWFROMPOINTstr(testTTM_WINDOWFROMPOINT_VMAJOR)
#define testTTM_WINDOWFROMPOINT_VMINORs testTTM_WINDOWFROMPOINTstr(testTTM_WINDOWFROMPOINT_VMINOR)
#define testTTM_WINDOWFROMPOINT_VPATCHs testTTM_WINDOWFROMPOINTstr(testTTM_WINDOWFROMPOINT_VPATCH)
#define testTTM_WINDOWFROMPOINT_VTAILs  testTTM_WINDOWFROMPOINTstr(testTTM_WINDOWFROMPOINT_VTAIL)

#define testTTM_WINDOWFROMPOINT_NAME "testTTM_WINDOWFROMPOINT"

enum {
	testTTM_WINDOWFROMPOINT_vmajor = testTTM_WINDOWFROMPOINT_VMAJOR,
	testTTM_WINDOWFROMPOINT_vminor = testTTM_WINDOWFROMPOINT_VMINOR,
	testTTM_WINDOWFROMPOINT_vpatch = testTTM_WINDOWFROMPOINT_VPATCH,
	testTTM_WINDOWFROMPOINT_vtail = testTTM_WINDOWFROMPOINT_VTAIL,
};


#endif
